name: bizhingebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bottom_navy_bar: ^6.1.0
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_nav_bar: ^5.0.7
  http: ^1.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
